### ISSUE TITLE
依赖与模型都下载好了后，出现的一个错误请协助排查

### ISSUE THREAD

**Issue by ss958** [AIFSH/hallo2-ComfyUI#1]
Traceback (most recent call last):
  File "F:\AI\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\AI\ComfyUI-aki-v1.4\custom_nodes\hallo2-ComfyUI\__init__.py", line 110, in gen_video
    save_seg_path = inference_process(config)
  File "F:\AI\ComfyUI-aki-v1.4\custom_nodes\hallo2-ComfyUI\inference_long.py", line 214, in inference_process
    source_image_lip_mask = image_processor.preprocess(
TypeError: ImageProcessor.preprocess() missing 1 required positional argument: 'task_model_path'

**Comment by goodluck821** [comment]
comfyui-hallo和hallo2-comfyui,下载后，按照所指出的配置依赖，都是用不了的，都是说缺少MODULE。一个说找不到hallo.pth,一个说没有hallo.animate。
